# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# re
# --------------------------------------------------------------------------

from azure.cli.core import AzCommandsLoader
from azext_{hero_name}._help import helps  # pylint: disable=unused-import
try:
    from azext_{hero_name}.manual._help import helps  # pylint: disable=reimported
except ImportError:
    pass


class {hero_name}ManagementClientCommandsLoader(AzCommandsLoader):

    def __init__(self, cli_ctx=None):
        from azure.cli.core.commands import CliCommandType
        from azext_{hero_name}._client_factory import cf_{hero_name}_cl
        {hero_name}_custom = CliCommandType(
            operations_tmpl='azext_{hero_name}.custom#{}',
            client_factory=cf_{hero_name}_cl)
        parent = super({hero_name}ManagementClientCommandsLoader, self)
        parent.__init__(cli_ctx=cli_ctx, custom_command_type={hero_name}_custom)

    def load_command_table(self, args):
        from azext_{hero_name}.commands import load_command_table
        load_command_table(self, args)
        try:
            from azext_{hero_name}.manual.commands import load_command_table as load_command_table_manual
            load_command_table_manual(self, args)
        except ImportError:
            pass
        return self.command_table

    def load_arguments(self, command):
        from azext_{hero_name}._params import load_arguments
        load_arguments(self, command)
        try:
            from azext_{hero_name}.manual._params import load_arguments as load_arguments_manual
            load_arguments_manual(self, command)
        except ImportError:
            pass


COMMAND_LOADER_CLS = {hero_name}ManagementClientCommandsLoader
