# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------


class DummyManagementClient(object):
    def __init__(
        self,
        credential,  # type: "TokenCredential"
        subscription_id,  # type: str
        base_url=None,  # type: Optional[str]
        **kwargs  # type: Any
    ):
        pass
        self.operation = None

    def close(self):
        pass

    def __enter__(self):
        pass

    def __exit__(self, *exc_details):
        pass

def cf_{hero_name}_cl(cli_ctx, *_):
    from azure.cli.core.commands.client_factory import get_mgmt_service_client
    return get_mgmt_service_client(cli_ctx,
                                   DummyManagementClient)


def cf_operation(cli_ctx, *_):
    return cf_{hero_name}_cl(cli_ctx).operation


def cf_{hero_name}_provider(cli_ctx, *_):
    return cf_{hero_name}_cl(cli_ctx).{hero_name}_provider
